### ISSUE TITLE
distant labeling

### ISSUE THREAD

**Issue by shainaraza** [mgruppi/nela-gt-2019#1]
Any guidance on labeling the data?
thanks

**Comment by mgruppi** [comment]
Hi @shainaraza,
The labels we provide for the data are computed by aggregating scores for each source from various news assessment agencies (Media Bias/Fact Check, AllSides, Politifact, etc.).
More specifically, it works as if each news agency voted for the reliability of each news source assigning 0 (reliable), 1 (mixed), 2 (unreliable) to it. We then aggregate the votes by a simple average of the votes, rounding to the nearest integer to decide on the final reliability score.
You can find more information in our paper https://arxiv.org/abs/2003.08444

Best

**Comment by shainaraza** [comment]
thanks a lot @mgruppi , I followed and I found the labels.
